[package]
name = "i3themes"
version = "0.1.0"
authors = ["lopukhov <12306261+lopukhov@users.noreply.github.com>"]

[dependencies]
clap = {version = "2.33", features = ["yaml"] }
serde = {version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
